In [72]:
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from datetime import datetime, date, time, timedelta

# File to Load (Remember to change these)
DB = "Orders Ago-Sept.csv"
DBTienda = "20190401 Base de tiendas WM y SA.csv"
Orders = pd.read_csv("Orders Ago-Sept.csv")
Stores = pd.read_csv("20190401 Base de tiendas WM y SA.csv")

In [73]:
Orders.head()

,folio,id_tipo,Estatus,ID Tienda,Nombre tienda,Fin de captura,Fecha de entrega,Hora de entrega,Dia Sem,Mes,Venta Neta,Código Postal,latitude,longitude
0,2458404,Pickup,Entregado,2735,LA CRUZ,29/07/2019 04:23,01/08/2019,8,Thu,8,3721.250000,0,NaN,NaN
1,2458898,Delivery,Entregado,4157,PERIFERICO CUAUTITLAN,29/07/2019 11:49,01/08/2019,8,Thu,8,2640.095000,54753,19.682599,-99.184573
2,2459734,Pickup,Entregado,3851,AEROPUERTO,29/07/2019 14:13,01/08/2019,8,Thu,8,1592.066667,0,NaN,NaN
3,2460626,Pickup,Entregado,3851,AEROPUERTO,29/07/2019 14:39,01/08/2019,8,Thu,8,1580.700000,0,NaN,NaN
4,2461535,Pickup,Entregado,3851,AEROPUERTO,29/07/2019 14:41,01/08/2019,8,Thu,8,1580.700000,0,NaN,NaN

In [74]:
Stores.head()

,Det,Nombre,Region,Estado,Ciudad,Municipio,Proto,Long,Lat,Con servicio?
0,4156,Cola De Ballena,Noroeste,Baja California Sur,La Paz,La Paz,SPCT-112,"-110,343,084","24,118,732",Sí
1,1724,Los Reyes Pza Zumpango,Centro,Mexico,ZM del Valle de México,Zumpango,SPCT-127,"-99,054,728","19,789,880",No
2,5791,Zinacantepec,Centro,Mexico,ZM de Toluca,Zinacantepec,SPCT-112,"-99,699,316","19,287,137",No
3,1686,La Cima,Occidente,Jalisco,ZM de Guadalajara,Zapopan,SPCT-112,"-103,411,119","20,744,996",No
4,3928,Guadalajara Parques,Occidente,Jalisco,ZM de Guadalajara,Zapopan,SPCT-112,"-103,449,000","20,659,000",No

In [75]:
Orders.dtypes

folio                 int64
id_tipo              object
Estatus              object
ID Tienda             int64
Nombre tienda        object
Fin de captura       object
Fecha de entrega     object
Hora de entrega       int64
Dia Sem              object
Mes                   int64
Venta Neta          float64
Código Postal         int64
latitude            float64
longitude           float64
dtype: object

In [76]:
Stores.dtypes

Det               int64
Nombre           object
Region           object
Estado           object
Ciudad           object
Municipio        object
Proto            object
Long             object
Lat              object
Con servicio?    object
dtype: object

In [77]:
Stores['Long'] = Stores['Long'].str.replace('([+,])', '', regex = True).astype('float')
Stores['Lat'] = Stores['Lat'].str.replace('([+,])', '', regex = True).astype('float')

In [78]:
Stores.head()

,Det,Nombre,Region,Estado,Ciudad,Municipio,Proto,Long,Lat,Con servicio?
0,4156,Cola De Ballena,Noroeste,Baja California Sur,La Paz,La Paz,SPCT-112,-110343084.0,24118732.0,Sí
1,1724,Los Reyes Pza Zumpango,Centro,Mexico,ZM del Valle de México,Zumpango,SPCT-127,-99054728.0,19789880.0,No
2,5791,Zinacantepec,Centro,Mexico,ZM de Toluca,Zinacantepec,SPCT-112,-99699316.0,19287137.0,No
3,1686,La Cima,Occidente,Jalisco,ZM de Guadalajara,Zapopan,SPCT-112,-103411119.0,20744996.0,No
4,3928,Guadalajara Parques,Occidente,Jalisco,ZM de Guadalajara,Zapopan,SPCT-112,-103449000.0,20659000.0,No

In [65]:
Stores.dtypes

Det                int64
Nombre            object
Region            object
Estado            object
Ciudad            object
Municipio         object
Proto             object
Long             float64
Lat              float64
Con servicio?     object
dtype: object

In [79]:
Stores['Long'] = Stores['Long']/1000000

In [80]:
Stores.head()

,Det,Nombre,Region,Estado,Ciudad,Municipio,Proto,Long,Lat,Con servicio?
0,4156,Cola De Ballena,Noroeste,Baja California Sur,La Paz,La Paz,SPCT-112,-110.343084,24118732.0,Sí
1,1724,Los Reyes Pza Zumpango,Centro,Mexico,ZM del Valle de México,Zumpango,SPCT-127,-99.054728,19789880.0,No
2,5791,Zinacantepec,Centro,Mexico,ZM de Toluca,Zinacantepec,SPCT-112,-99.699316,19287137.0,No
3,1686,La Cima,Occidente,Jalisco,ZM de Guadalajara,Zapopan,SPCT-112,-103.411119,20744996.0,No
4,3928,Guadalajara Parques,Occidente,Jalisco,ZM de Guadalajara,Zapopan,SPCT-112,-103.449000,20659000.0,No

In [83]:
Stores['Lat'] = Stores['Lat']/10

In [84]:
Stores.head()

,Det,Nombre,Region,Estado,Ciudad,Municipio,Proto,Long,Lat,Con servicio?
0,4156,Cola De Ballena,Noroeste,Baja California Sur,La Paz,La Paz,SPCT-112,-110.343084,24.118732,Sí
1,1724,Los Reyes Pza Zumpango,Centro,Mexico,ZM del Valle de México,Zumpango,SPCT-127,-99.054728,19.789880,No
2,5791,Zinacantepec,Centro,Mexico,ZM de Toluca,Zinacantepec,SPCT-112,-99.699316,19.287137,No
3,1686,La Cima,Occidente,Jalisco,ZM de Guadalajara,Zapopan,SPCT-112,-103.411119,20.744996,No
4,3928,Guadalajara Parques,Occidente,Jalisco,ZM de Guadalajara,Zapopan,SPCT-112,-103.449000,20.659000,No

In [85]:
Stores.to_json(r'Stores.json',orient='split')

In [86]:
df = Orders.merge(Stores, "Orders.ID Tienda"=="Stores.Det", how='left')

TypeError: merge() got multiple values for argument 'how'